preprocessing:
  mask: True
  collate_fn: masks
  natoms: 286
splitting:
  split: random
  file_folds: test_split_e3nn
  id_fold: 0

training_params:
  mode: no_attention
  log_step: 10
  save_step: 10
  encoder_name: encoder_best_0.ckpt
  decoder_name: decoder_best_0.ckpt
  n_splits: 5


  
model:
  encoder: resnet_bio_local_net
  encoder_kwargs:
    encoding: linear
    max_rad: 1
    num_basis: 3
    n_neurons: 150
    n_layers: 2
    beta: 5
    rad_model: gaussian
    num_embeddings: 6
    embed: 40
    list_harm: "[[(40, 0)], [(40, 0)]]"
    scalar_act_name:  sp
    gate_act_name: sigmoid
    fc_sizes: "[[40, 40], [40, 160]]"
    aggregation_mode: avg

  
  decoder: lstm
  decoder_kwargs:
    vocab_size: 52
    vocab_path: ../data/new_vocab.pkl
    embed_size: 160
    hidden_size: 160
    num_layers: 1
    beam_size: 20

model_params: 
  model_name: bio_local_resnet_34
  num_epochs: 30
  batch_size: 10
  n_splits: 5
  num_workers: 1
  learning_rate: 0.0005


output_parameters: 
  savedir: ../results/captioning_results


sampling_params: 
  number_smiles: 30
  time_waiting: 300
  type_fold: random
  id_fold: 0
  folds: ../results/captioning_results/e3nn_1/logs/idx/test_idx_0
  file_stat: 0_fold_stat.csv
  sampling_data: test
  name_all_stat: stat_e3nn_prob_0.csv