preprocessing:
  mask: True
  collate_fn: masks
  natoms: 289
splitting:
  split: random
  file_folds: test_random_split_att_vis_18_09
  id_fold: 0

training_params:
  mode: attention
  log_step: 10
  save_step: 10
  encoder_name: encoder_best_0.ckpt
  decoder_name: decoder_best_0.ckpt
  n_splits: 5
  alpha_c: 1
  loss_mode: double_stochastic
model:
  encoder: network1_vis
  encoder_kwargs:
    max_rad: 2
    num_basis: 10
    n_neurons: 60
    n_layers: 2
    beta: 5
    rad_model: gaussian
    num_embeddings: 6
    embed: 21
    l0: 21
    L: 1
    scalar_act_name:  sp
    gate_act_name: sigmoid
    natoms: 289
    mlp_h: 40
    Out: 1
    aggregation_mode: avg

  
  decoder: lstm_attention_vis
  decoder_kwargs:
    attention_dim: 80
    embed_dim: 80
    decoder_dim: 80
    vocab_size: 32
    vocab_path: ../data/vocab.pkl
    encoder_dim: 80
    dropout: 0.5

model_params: 
  model_name: "e3nn"
  num_epochs: 1
  batch_size: 4
  n_splits: 5
  num_workers: 1
  learning_rate: 0.001
  input_channels: 22
  feature_type: with_labels
  representations: [(23,), (2, 2), (4, 4), (10,)]


output_parameters: 
  savedir: ../results/captioning_results/test_e3nn


sampling_params: 
  sampling: probabilistic
  sample_id: 15
  number_smiles: 1
  time_waiting: 5
  type_fold: random
  id_fold: 0
  folds: ../results/captioning_results/e3nn_1/logs/idx/test_idx_0
  file_stat: 0_fold_stat.csv
  sampling_data: test
  name_all_stat: stat_e3nn_prob_0.csv