preprocessing:
  mask: True
  collate_fn: masks
  natoms: 286
  vocab_path: ../data/vocab.pkl
splitting:
  split: random
  file_folds: random_split_test
  id_fold: 0

training_params:
  mode: no_attention
  log_step: 10
  save_step: 10
  encoder_name: encoder_best_0.ckpt
  decoder_name: decoder_best_0.ckpt
  n_splits: 5
model:
  encoder: network1
  encoder_kwargs:
    max_rad: 2
    num_basis: 3
    n_neurons: 20
    n_layers: 2
    beta: 5
    rad_model: gaussian
    num_embeddings: 6
    embed: 4
    l0: 4
    L: 1
    scalar_act_name:  sp
    gate_act_name: sigmoid
    natoms: 286
    mlp_h: 21
    Out: 1
    aggregation_mode: avg

  

  decoder: lstm
  decoder_kwargs:
    vocab_size: 32
    vocab_path: ../data/vocab.pkl
    embed_size: 42
    hidden_size: 42
    num_layers: 1
    beam_size: 20


model_params: 
  model_name: "e3nn"
  num_epochs: 1
  batch_size: 4
  n_splits: 5
  num_workers: 1
  learning_rate: 0.001
  input_channels: 22
  feature_type: with_labels
  representations: [(23,), (2, 2), (4, 4), (10,)]


output_parameters: 
  savedir: ../results/captioning_results/test_e3nn


sampling_params: 
  sampling: probabilistic
  sample_id: 15
  number_smiles: 3
  time_waiting: 10
  type_fold: random
  id_fold: 0
  folds: ../results/captioning_results/e3nn_1/logs/idx/test_idx_0
  file_stat: 0_fold_stat.csv
  sampling_data: test
  name_all_stat: stat_e3nn_prob_0.csv