data:
  path: ../data/new_refined
  vocab_path: ../data/new_vocab
  path_refined: ../data/new_refined
  selection: filtered
training_params:
  image_dir: ../data/new_refined
  caption_path: ../data/new_refined

preprocessing:
  vocab_path: ../data/new_vocab
  path_root: ..
  selection: filtered
  