preprocessing:
  mask: True
  collate_fn: masks
training_params:
  log_step: 10
  save_step: 1
  encoder_path: encoder-20-600.ckpt
  decoder_path: decoder-20-600.ckpt
  n_splits: 5
model:
  encoder: network1
  encoder_kwargs:
    max_rad: 2
    num_basis: 50
    n_neurons: 100
    n_layers: 2
    beta: 5
    rad_model: gaussian
    embed: 20
    l0: 20
    L: 2
    scalar_act_name:  sp
    gate_act_name: sigmoid
    avg_n_atoms: 286
    mlp_h: 50
    Out: 1
    aggregation_mode: avg

  decoder: lstm
  decoder_kwargs:
    vocab_size: 32
    embed_size: 100
    hidden_size: 100
    num_layers: 1


model_params: 
  model_name: "e3nn"
  num_epochs: 1
  batch_size: 4
  n_splits: 5
  num_workers: 1
  learning_rate: 0.001
  input_channels: 22
  feature_type: with_labels
  representations: [(23,), (2, 2), (4, 4), (10,)]


output_parameters: 
  savedir: ../results/captioning_results/se3cnn_fast_1


sampling_params: 
  sampling: probabilistic
  sample_id: 15
  number_smiles: 3
  time_waiting: 25
  type_fold: O
  id_fold: 0
  folds: ../results/captioning_results/se3cnn_fast_1/logs/test_idx_0
  file_stat: 0_fold_stat.csv

