training_params:
  log_step: 10
  save_step: 1
  encoder_name: encoder-1-1-965.ckpt
  decoder_name: decoder-20-600.ckpt
model:
  encoder: resnet
  encoder_kwargs:
    lat_out: 256
    emb_dim: 10
    Z: True
    feature_collation: pool
    num_embeddings: 6
  decoder: lstm
  decoder_kwargs:
    vocab_size: 32
    embed_size: 256
    hidden_size: 256
    num_layers: 1


model_params: 
  model_name: "e3nn"
  num_epochs: 20
  batch_size: 4
  n_splits: 5
  num_workers: 2
  learning_rate: 0.001
  input_channels: 22
  feature_type: with_labels
  representations: [(23,), (2, 2), (4, 4), (10,)]


output_parameters: 
  savedir: ../results/captioning_results/cv/resnet_1/


sampling_params: 
  sampling: probabilistic
  sample_id: 15
  number_smiles: 3
  time_waiting: 25
  type_fold: O
  id_fold: 0
  folds: ../results/captioning_results/cv/resnet_1/logs/test_idx_0
  file_stat: 0_fold_stat.csv

