training_params:
  log_step: 10
  save_step: 1
  encoder_path: encoder-20-600.ckpt
  decoder_path: decoder-20-600.ckpt
model:
  encoder: se3cnn
  encoder_kwargs:
    nclouds: 5
    emb_dim: 10
    neighborradius: 2
    cloudord: 2
    cloud_dim: 5
    natoms: 286
    nffl: 1
    ffl1size: 512
    num_embeddings: 6
    nradial: 3
    nbasis: 3
    rad_neurons: 100
  decoder: lstm
  decoder_kwargs:
    vocab_size: 32
    embed_size: 100
    hidden_size: 100
    num_layers: 1


model_params: 
  model_name: "e3nn"
  num_epochs: 1
  batch_size: 4
  n_splits: 5
  num_workers: 2
  learning_rate: 0.001
  input_channels: 22
  feature_type: with_labels
  representations: [(23,), (2, 2), (4, 4), (10,)]


output_parameters: 
  savedir: ../results/captioning_results/se3cnn_1


sampling_params: 
  sampling: probabilistic
  sample_id: 15
  number_smiles: 3
  time_waiting: 25
  type_fold: O
  id_fold: 0
  folds: ../results/captioning_results/se3cnn_1/logs/test_idx_0
  file_stat: 0_fold_stat.csv

